# Selected - 100 numpy exercises with hint

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [0]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [4]:
np.__version__

'1.14.5'

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [6]:
v = np.zeros(10)
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [7]:
np.size(v)

10

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [9]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [10]:
vr = v[::-1]
vr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [0]:
#mention argmax

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [0]:
#along the axis too

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [20]:
#0 * np.nan
#np.nan == np.nan
#np.inf > np.nan
#np.nan - np.nan
#0.3 == 3.0 * 0.1

nan

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [16]:
v = np.arange(15)
v
v[(v>3) & (v<8)] *= -1
v

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [0]:
np.multiply(np.add(a,b),np.divide(np.multiply(a,-1),2))

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [13]:
Z = np.random.uniform(0,10,10)
Z.astype(int)
print (np.trunc(Z))


array([6, 8, 6, 3, 0, 7, 5, 0, 8, 3])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [0]:
#broadcasting

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [5]:
import numpy as np

Z = np.linspace(0,1,11,endpoint=True)[1:-1]
print(Z)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [43]:
v = np.random.randint(10,102,(1,10))
print (v)

[[43 22 67 74 98 10 62 10 87 74]]


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [0]:
# whats rtol and atol

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [47]:
v = np.random.rand(10)
v
v.sort()
v[-1]

0.9399530153438614

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [54]:
a = np.random.random(10)
a
b = np.random.random(10)
b

c = np.subtract(a,b)
c

d= np.subtract.outer(a,b)
d

array([[ 0.0790225 , -0.65156649, -0.03411564, -0.18691293, -0.21905923,
        -0.41186756,  0.13749135, -0.60016976,  0.108225  , -0.44241743],
       [ 0.7350454 ,  0.00445642,  0.62190727,  0.46910998,  0.43696368,
         0.24415535,  0.79351426,  0.05585315,  0.76424791,  0.21360548],
       [ 0.42895149, -0.30163749,  0.31581336,  0.16301606,  0.13086977,
        -0.06193856,  0.48742034, -0.25024076,  0.458154  , -0.09248843],
       [-0.06758997, -0.79817896, -0.18072811, -0.3335254 , -0.3656717 ,
        -0.55848002, -0.00912112, -0.74678222, -0.03838747, -0.5890299 ],
       [-0.09703408, -0.82762306, -0.21017221, -0.36296951, -0.3951158 ,
        -0.58792413, -0.03856523, -0.77622633, -0.06783157, -0.61847401],
       [-0.12591684, -0.85650582, -0.23905497, -0.39185227, -0.42399856,
        -0.61680689, -0.06744799, -0.80510909, -0.09671433, -0.64735677],
       [ 0.50354792, -0.22704106,  0.39040978,  0.23761249,  0.20546619,
         0.01265787,  0.56201677, -0.17564433

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [12]:
for i,j in enumerate(np.arange(10)):
  print (i,j)

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [27]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [26]:
Z = np.random.randint(0,10,50)
np.bincount(Z)
#print(np.bincount(Z).argmax())

array([5, 3, 7, 6, 1, 2, 8, 8, 5, 5])